//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team8_ADProjectLUStationerySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class adjustmentDetail
    {
        public int adjustmentDetailsId { get; set; }
        public int adjustmentId { get; set; }
        public string itemCode { get; set; }
        public Nullable<int> adjustmentQuantity { get; set; }
        public Nullable<double> adjustmentAmount { get; set; }
        public string type { get; set; }
        public string reason { get; set; }
    
        public virtual adjustment adjustment { get; set; }
        public virtual catelogueItem catelogueItem { get; set; }
    }
}
