//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team8_ADProjectLUStationerySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class adjustment
    {
        public adjustment()
        {
            this.adjustmentDetails = new HashSet<adjustmentDetail>();
        }
    
        public int adjustmentId { get; set; }
        public Nullable<double> totalAmount { get; set; }
        public string status { get; set; }
        public string authorizedPerson { get; set; }
        public Nullable<int> employeeId { get; set; }
        public Nullable<System.DateTime> adjustDate { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual ICollection<adjustmentDetail> adjustmentDetails { get; set; }
    }
}
