//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team8_ADProjectLUStationerySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class catelogueItem
    {
        public catelogueItem()
        {
            this.adjustmentDetails = new HashSet<adjustmentDetail>();
            this.disbursementDetails = new HashSet<disbursementDetail>();
            this.purchaseDetails = new HashSet<purchaseDetail>();
            this.requisitionDetails = new HashSet<requisitionDetail>();
            this.retrievalDetails = new HashSet<retrievalDetail>();
            this.stockCards = new HashSet<stockCard>();
        }
    
        public string itemCode { get; set; }
        public Nullable<int> categoryId { get; set; }
        public string itemDescription { get; set; }
        public Nullable<int> reorderLevel { get; set; }
        public Nullable<int> reorderQuantity { get; set; }
        public string uom { get; set; }
        public Nullable<double> tenderPrice { get; set; }
        public string bin { get; set; }
        public Nullable<int> quantity { get; set; }
        public string photos { get; set; }
    
        public virtual ICollection<adjustmentDetail> adjustmentDetails { get; set; }
        public virtual category category { get; set; }
        public virtual ICollection<disbursementDetail> disbursementDetails { get; set; }
        public virtual ICollection<purchaseDetail> purchaseDetails { get; set; }
        public virtual ICollection<requisitionDetail> requisitionDetails { get; set; }
        public virtual ICollection<retrievalDetail> retrievalDetails { get; set; }
        public virtual ICollection<stockCard> stockCards { get; set; }
    }
}
