//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team8_ADProjectLUStationerySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class collectionPoint
    {
        public collectionPoint()
        {
            this.departments = new HashSet<department>();
            this.disbursements = new HashSet<disbursement>();
        }
    
        public int collectionPointId { get; set; }
        public string collectionPointName { get; set; }
        public string collectionPointDescription { get; set; }
        public string latitude { get; set; }
        public string longtitude { get; set; }
        public Nullable<System.TimeSpan> collectionTime { get; set; }
    
        public virtual ICollection<department> departments { get; set; }
        public virtual ICollection<disbursement> disbursements { get; set; }
    }
}
