//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team8_ADProjectLUStationerySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class department
    {
        public department()
        {
            this.disbursements = new HashSet<disbursement>();
            this.employees = new HashSet<employee>();
            this.requisitions = new HashSet<requisition>();
            this.retrievalDetails = new HashSet<retrievalDetail>();
        }
    
        public string departmentCode { get; set; }
        public string departmentName { get; set; }
        public string contactName { get; set; }
        public Nullable<int> telephoneNo { get; set; }
        public string FaxNo { get; set; }
        public string headName { get; set; }
        public Nullable<int> collectionPointId { get; set; }
        public string photos { get; set; }
        public Nullable<int> RepresentativeID { get; set; }
    
        public virtual collectionPoint collectionPoint { get; set; }
        public virtual ICollection<disbursement> disbursements { get; set; }
        public virtual ICollection<employee> employees { get; set; }
        public virtual ICollection<requisition> requisitions { get; set; }
        public virtual ICollection<retrievalDetail> retrievalDetails { get; set; }
    }
}
