//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team8_ADProjectLUStationerySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class disbursementDetail
    {
        public int disbursementId { get; set; }
        public string itemCode { get; set; }
        public Nullable<int> reqQuantity { get; set; }
        public Nullable<int> receivedQuantity { get; set; }
        public Nullable<bool> marks { get; set; }
    
        public virtual catelogueItem catelogueItem { get; set; }
        public virtual disbursement disbursement { get; set; }
        public virtual disbursement disbursement1 { get; set; }
    }
}
