//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team8_ADProjectLUStationerySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class disbursement
    {
        public disbursement()
        {
            this.disbursementDetails = new HashSet<disbursementDetail>();
            this.disbursementDetails1 = new HashSet<disbursementDetail>();
        }
    
        public int disbursementId { get; set; }
        public string departmentCode { get; set; }
        public Nullable<int> employeeId { get; set; }
        public Nullable<int> collectionId { get; set; }
        public Nullable<System.DateTime> collectionDate { get; set; }
        public string status { get; set; }
        public Nullable<int> RetrivalId { get; set; }
    
        public virtual collectionPoint collectionPoint { get; set; }
        public virtual department department { get; set; }
        public virtual ICollection<disbursementDetail> disbursementDetails { get; set; }
        public virtual retrieval retrieval { get; set; }
        public virtual retrieval retrieval1 { get; set; }
        public virtual employee employee { get; set; }
        public virtual ICollection<disbursementDetail> disbursementDetails1 { get; set; }
    }
}
