//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team8_ADProjectLUStationerySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchaseOrder
    {
        public purchaseOrder()
        {
            this.purchaseDetails = new HashSet<purchaseDetail>();
        }
    
        public int purchaseorderno { get; set; }
        public string supplierCode { get; set; }
        public Nullable<System.DateTime> purchaseDate { get; set; }
        public string status { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<double> totalAmount { get; set; }
    
        public virtual ICollection<purchaseDetail> purchaseDetails { get; set; }
        public virtual supplier supplier { get; set; }
    }
}
