//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team8_ADProjectLUStationerySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchaseDetail
    {
        public int purchaseDetail_Id { get; set; }
        public int purchaseOrderno { get; set; }
        public string itemCode { get; set; }
        public string itemDescription { get; set; }
        public Nullable<int> orderedQuantity { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<double> amount { get; set; }
        public Nullable<int> receivedQuantity { get; set; }
    
        public virtual catelogueItem catelogueItem { get; set; }
        public virtual purchaseOrder purchaseOrder { get; set; }
    }
}
