//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team8_ADProjectLUStationerySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class requisition
    {
        public requisition()
        {
            this.requisitionDetails = new HashSet<requisitionDetail>();
            this.retrievalRequisitions = new HashSet<retrievalRequisition>();
        }
    
        public int requisitionId { get; set; }
        public string departmentCode { get; set; }
        public Nullable<int> employeeId { get; set; }
        public Nullable<int> statusId { get; set; }
        public Nullable<System.DateTime> requisitionDate { get; set; }
        public Nullable<bool> selfCollection { get; set; }
    
        public virtual department department { get; set; }
        public virtual employee employee { get; set; }
        public virtual requisitionStatu requisitionStatu { get; set; }
        public virtual ICollection<requisitionDetail> requisitionDetails { get; set; }
        public virtual ICollection<retrievalRequisition> retrievalRequisitions { get; set; }
    }
}
