//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team8_ADProjectLUStationerySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class requisitionStatu
    {
        public requisitionStatu()
        {
            this.requisitions = new HashSet<requisition>();
        }
    
        public int statusId { get; set; }
        public string statusDescription { get; set; }
    
        public virtual ICollection<requisition> requisitions { get; set; }
    }
}
