//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team8_ADProjectLUStationerySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class retrieval
    {
        public retrieval()
        {
            this.disbursements = new HashSet<disbursement>();
            this.disbursements1 = new HashSet<disbursement>();
            this.retrievalDetails = new HashSet<retrievalDetail>();
            this.retrievalRequisitions = new HashSet<retrievalRequisition>();
        }
    
        public int retrievalId { get; set; }
        public string status { get; set; }
    
        public virtual ICollection<disbursement> disbursements { get; set; }
        public virtual ICollection<disbursement> disbursements1 { get; set; }
        public virtual ICollection<retrievalDetail> retrievalDetails { get; set; }
        public virtual ICollection<retrievalRequisition> retrievalRequisitions { get; set; }
    }
}
