//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team8_ADProjectLUStationerySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class retrievalRequisition
    {
        public int id { get; set; }
        public Nullable<int> retrievalId { get; set; }
        public Nullable<int> requisitionId { get; set; }
    
        public virtual requisition requisition { get; set; }
        public virtual retrieval retrieval { get; set; }
    }
}
