//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team8_ADProjectLUStationerySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class role
    {
        public role()
        {
            this.userDetails = new HashSet<userDetail>();
        }
    
        public int roleId { get; set; }
        public string roleDescription { get; set; }
    
        public virtual ICollection<userDetail> userDetails { get; set; }
    }
}
