//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team8_ADProjectLUStationerySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class stockCard
    {
        public int transactionId { get; set; }
        public string itemCode { get; set; }
        public Nullable<System.DateTime> transactionDate { get; set; }
        public string transactionType { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> balance { get; set; }
    
        public virtual catelogueItem catelogueItem { get; set; }
    }
}
