//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team8_ADProjectLUStationerySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class userDetail
    {
        public int userId { get; set; }
        public string password { get; set; }
        public Nullable<int> roleId { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual role role { get; set; }
    }
}
