//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team8_ADProjectLUStationerySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class VS_ORDER
    {
        public string itemCode { get; set; }
        public string itemDescription { get; set; }
        public string query { get; set; }
        public Nullable<int> totalOrderQty { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<double> totalAmount { get; set; }
    }
}
